esphome:
  name: priza-pc
  friendly_name: priza-pc

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_smart
  password: !secret wifi_smart_pass
  ap:
    ssid: "Priza-Pc Fallback Hotspot"
    password: "KnS9xJl2Tnj4"

substitutions:
  voltage_divider: "778"
  current_resistor: "0.001008755324183625"
  current_multiply: "0.3100151976971161"


sensor:
  - platform: uptime
    name: Uptime
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
    sel_pin:
      number: P24
      inverted: true
    current:
      name: Priza PC Current
      filters:
        - multiply: ${current_multiply}
    voltage:
      name: Priza PC Voltage
    power:
      name: Priza PC Power
    energy:
      name: Priza PC Energy Total
    voltage_divider: ${voltage_divider}
    current_resistor: ${current_resistor}
    update_interval: 2s

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Priza PC
    restore_mode:
      RESTORE_DEFAULT_ON
    pin: P26
    on_turn_on:
      - light.turn_on: light_status
    on_turn_off:
      - light.turn_off: light_status

light:
  - platform: status_led
    id: light_status
    pin:
      number: P8
      inverted: true
