#This device have inching inside code

esphome:
  name: poarta-intrare

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid_libre
  password: !secret wifi_password_libre
  ap:

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version
  - platform: wifi_info
    ip_address:
      name: 'Poarta IP Address'
    ssid:
      name: 'Poarta Connected SSID'
    bssid:
      name: 'Poarta Connected BSSID'
    mac_address:
      name: 'Poarta Mac Wifi Address'
    scan_results:
      name: 'Poarta Latest Scan Results'
    dns_address:
      name: 'Poarta DNS Address'
sensor:
  - platform: uptime
    name: Uptime

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P8
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
  - platform: gpio
    id: binary_switch_2
    pin:
      number: P9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_2
  - platform: gpio
    id: binary_switch_3
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_3
  - platform: gpio
    id: binary_switch_4
    pin:
      number: P11
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_4
  - platform: gpio
    id: binary_switch_all
    pin:
      number: P7
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
        - switch.toggle: switch_2
        - switch.toggle: switch_3
        - switch.toggle: switch_4

switch:
  - platform: gpio
    id: switch_1
    name: Open Gate
    pin: P24
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: switch_1
  - platform: gpio
    id: switch_2
    name: Close Gate
    pin: P6
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: switch_2
  - platform: gpio
    id: switch_3
    name: Stop Gate
    pin: P26
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: switch_3
  - platform: gpio
    id: switch_4
    name: Gate SbS
    pin: P14
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: switch_4

status_led:
  pin:
    number: P22
    inverted: true
